# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - projetocloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://projetocloud.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1054c6b7f9d043b1ba3449f3973007a9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_71df83c17264411097c89bad6f12ab5e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: projetocloud.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1054c6b7f9d043b1ba3449f3973007a9 }}/ap2-cloud-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'projetocloud'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_476853ff7f4e46b4954dde1a3b06e15b }}
        images: 'projetocloud.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1054c6b7f9d043b1ba3449f3973007a9 }}/ap2-cloud-app:${{ github.sha }}'