name: Build and deploy container app to Azure Web App - projetoCloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: projetocloud.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername_768f325ca9284813ab53d412ca7384f7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_62da35bf75f845a98343c826153e64ad }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: projetocloud.azurecr.io/${{ toLower(secrets.AzureAppService_ContainerUsername_768f325ca9284813ab53d412ca7384f7) }}/ap2cloud-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'projetoCloud'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_68da25a7ad5a41dfba68a979c4b43bdd }}
        images: 'projetocloud.azurecr.io/${{ toLower(secrets.AzureAppService_ContainerUsername_768f325ca9284813ab53d412ca7384f7) }}/ap2cloud-app:${{ github.sha }}'
